<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_sobre</name>
   <tag></tag>
   <elementGuidId>2a2f6369-faf8-4f32-8b29-45558983b67a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='ember498']/div[2]/div/div/div/h2/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ember498 > div.pvs-header__container > div.pvs-header__top-container--no-stack > div.pvs-header__left-container--stack > div.pvs-header__title-container > h2.pvs-header__title.text-heading-large > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cfa757eb-a5e1-414b-a2c2-741ae35442d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0ed1e0ef-f3c3-40fd-8389-7b35c46b5f02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sobre</value>
      <webElementGuid>e44cae6a-84a0-4418-a225-b7fb83395004</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ember498&quot;)/div[@class=&quot;pvs-header__container&quot;]/div[@class=&quot;pvs-header__top-container--no-stack&quot;]/div[@class=&quot;pvs-header__left-container--stack&quot;]/div[@class=&quot;pvs-header__title-container&quot;]/h2[@class=&quot;pvs-header__title
              text-heading-large&quot;]/span[1]</value>
      <webElementGuid>48e490a9-ca0d-482a-b1b0-42d275c0e5d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='ember498']/div[2]/div/div/div/h2/span</value>
      <webElementGuid>a1389358-1b66-40e3-8040-6aaed6de0bd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Veja e gerencie suas conexões e interesses.'])[2]/following::span[2]</value>
      <webElementGuid>15e1f372-2f8c-436a-a327-c76205fcc188</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sobre'])[2]/preceding::span[1]</value>
      <webElementGuid>a7af726b-8282-456c-ab19-ea0e854872e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Em construção'])[2]/preceding::span[3]</value>
      <webElementGuid>32fc2c68-5223-40b7-9203-5e605a062b4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sobre']/parent::*</value>
      <webElementGuid>f00d0973-5f9e-4de3-949f-dca6838595a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[6]/div[2]/div/div/div/h2/span</value>
      <webElementGuid>4e200e9a-1496-4aba-9ab8-8e69e2dbca4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Sobre' or . = 'Sobre')]</value>
      <webElementGuid>547aee44-0702-4387-9a1a-efe493cb7d14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
