<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_sobre</name>
   <tag></tag>
   <elementGuidId>50dc87d6-34ec-417b-96de-81cba2e54f2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='multiline-text-form-component-profileEditFormElement-SUMMARY-profile-ACoAAEGZ9yMB3eIaculwldlT4U4DoW-vnZyLRhM-summary']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#multiline-text-form-component-profileEditFormElement-SUMMARY-profile-ACoAAEGZ9yMB3eIaculwldlT4U4DoW-vnZyLRhM-summary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>d6a55998-7691-4055-9940-1a3d53d9365d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fb-multiline-text  artdeco-text-input--input artdeco-text-input__textarea artdeco-text-input__textarea--align-top katalonDeHighlight</value>
      <webElementGuid>ef0b098b-815c-4a45-a811-2e6cb8c62d3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>multiline-text-form-component-profileEditFormElement-SUMMARY-profile-ACoAAEGZ9yMB3eIaculwldlT4U4DoW-vnZyLRhM-summary</value>
      <webElementGuid>b2b355f5-2d98-4204-89a1-e8c5239d999d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>c7ec0d70-e965-43eb-9e4c-6f0334475a64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>multiline-text-form-component-profileEditFormElement-SUMMARY-profile-ACoAAEGZ9yMB3eIaculwldlT4U4DoW-vnZyLRhM-summary-error ember369-char-limit</value>
      <webElementGuid>850edcec-1e02-4171-92f1-363e733fb36c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-artdeco-is-focused</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>054f2eeb-9a48-45b9-bfe9-da85863045c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;multiline-text-form-component-profileEditFormElement-SUMMARY-profile-ACoAAEGZ9yMB3eIaculwldlT4U4DoW-vnZyLRhM-summary&quot;)</value>
      <webElementGuid>0ec795ae-777f-4ebc-96cc-387d17fb402b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='multiline-text-form-component-profileEditFormElement-SUMMARY-profile-ACoAAEGZ9yMB3eIaculwldlT4U4DoW-vnZyLRhM-summary']</value>
      <webElementGuid>777ec331-17d0-41e9-9cc2-0cd0d7342272</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ember370']/textarea</value>
      <webElementGuid>63176e94-e9af-49c2-87dc-ef98d6ac6b49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>007d01ef-d310-415f-b5bb-f2c2685640d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'multiline-text-form-component-profileEditFormElement-SUMMARY-profile-ACoAAEGZ9yMB3eIaculwldlT4U4DoW-vnZyLRhM-summary']</value>
      <webElementGuid>896330f6-0b8b-4ad9-bd59-468def7dab7d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
