<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_senha</name>
   <tag></tag>
   <elementGuidId>7f75d6c5-d8ff-441e-9895-3d6962a82778</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#session_password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='session_password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c282cb15-b87c-4a6d-b2b6-50d5dceb6431</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input__input</value>
      <webElementGuid>1e777bb9-d6fd-40cd-b2e4-461ce846626b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>current-password</value>
      <webElementGuid>60abf5ea-5adf-44f8-8dbd-6b190d13b24a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>495de601-c4c3-4361-a024-155669f4a0a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>session_password</value>
      <webElementGuid>040f3493-4882-4669-8b10-93bcf10af407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>session_password</value>
      <webElementGuid>7ee3c34c-daf2-4855-8489-f4fb702b3bfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>d938d03a-85fc-45d7-a132-369103335512</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;session_password&quot;)</value>
      <webElementGuid>fedfe6d0-9f2a-43ec-821b-190afb566e36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='session_password']</value>
      <webElementGuid>31554054-32e7-42cd-8c61-da3759117415</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/section/div/div/form/div[2]/div[2]/input</value>
      <webElementGuid>5b35b220-3c0d-449e-8be7-4a075bf32105</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>18f945df-6310-4d74-bd5a-663a9a947536</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'session_password' and @name = 'session_password' and @type = 'password']</value>
      <webElementGuid>03c18a71-7a99-4a4f-a1ab-fe88b2e23827</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
