<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mensagem_senha_invalida</name>
   <tag></tag>
   <elementGuidId>46f6591a-2c1e-4cb1-ba63-1f200cbc405a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#error-for-password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='error-for-password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>988a9c82-8de9-46ef-b843-225694bbb846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>error-for</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>5c19e73c-88cb-4698-ab50-a5c8b7757ffa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>error-for-password</value>
      <webElementGuid>19cdd87b-6828-42ad-823d-dd064cb5c95a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form__label--error  </value>
      <webElementGuid>f5650953-5838-4b81-8b88-7f1ed622a53b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>204afad3-820c-4de7-bc29-a413f35ff502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>assertive</value>
      <webElementGuid>2ac421c1-d785-410c-b3d4-028b7ed8ecfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Senha incorreta. Esqueceu a senha?</value>
      <webElementGuid>a0df52c7-0177-4f63-9b36-8c5acd1ca231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;error-for-password&quot;)</value>
      <webElementGuid>d503e409-1beb-4544-ba59-bacfaa23b104</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='error-for-password']</value>
      <webElementGuid>afacc9ad-120a-4be0-871a-723415b4aa00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='organic-div']/form/div[2]/div</value>
      <webElementGuid>184beab6-1efb-4f24-9a37-07d3637cb0b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='exibir'])[1]/following::div[1]</value>
      <webElementGuid>2a583a69-ff7b-4bd4-8b99-374eed7f1583</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Entrar'])[1]/following::div[4]</value>
      <webElementGuid>1574106d-c734-444e-9c79-8c4672861812</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Esqueceu a senha?'])[2]/preceding::div[1]</value>
      <webElementGuid>3e341f44-36d2-46c1-85cf-3832781e08ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Senha incorreta.']/parent::*</value>
      <webElementGuid>b57f16bb-8283-4e55-803f-bb3f16534e7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div</value>
      <webElementGuid>fa71cbb7-8292-4459-860a-d473d6b4eba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'error-for-password' and (text() = 'Senha incorreta. Esqueceu a senha?' or . = 'Senha incorreta. Esqueceu a senha?')]</value>
      <webElementGuid>3710ec63-1b41-45a7-a05a-1651258d17af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
