<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_perfil</name>
   <tag></tag>
   <elementGuidId>1624f713-0cdf-4926-ad58-0945a6eeb158</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='ember15']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ember15</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9cf7a7ee-3fe7-4919-8de3-a67ade24925a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>ef30746d-8e02-4577-9618-5b54e40ac364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://media.licdn.com/dms/image/D4E03AQFn8Wx4jW5g2w/profile-displayphoto-shrink_100_100/0/1677799325404?e=1683158400&amp;v=beta&amp;t=x8NQjox6LVKWEn_ma33pwGGHOY0NOcnBuP8nYOBq79o</value>
      <webElementGuid>87203b03-8fec-4d23-babd-694e2d81c1a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>865e32e5-51ae-44a9-ba1b-aec506f0c6e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>José Silva</value>
      <webElementGuid>56f1f607-998b-4cc6-a4f7-5b1b4fc3bc9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ember15</value>
      <webElementGuid>848621ba-0dee-4cc9-a26c-1640c1d33b8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>global-nav__me-photo ember-view</value>
      <webElementGuid>5778eaf5-3522-4fe2-ab52-91cc2ccd37ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ember15&quot;)</value>
      <webElementGuid>98620fdc-4a7b-48aa-982c-b4c2e7cf1a49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='ember15']</value>
      <webElementGuid>cfdcdb9e-6ef5-4c4c-ad19-03469b3acde2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='ember14']/img</value>
      <webElementGuid>724c8be6-3ede-470c-a138-3419d683ca1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='José Silva']</value>
      <webElementGuid>7b5c5b92-16cd-433b-a525-d7753faf563e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>96dc517d-5498-4a49-b0a7-ae7685424912</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://media.licdn.com/dms/image/D4E03AQFn8Wx4jW5g2w/profile-displayphoto-shrink_100_100/0/1677799325404?e=1683158400&amp;v=beta&amp;t=x8NQjox6LVKWEn_ma33pwGGHOY0NOcnBuP8nYOBq79o' and @alt = 'José Silva' and @id = 'ember15']</value>
      <webElementGuid>ff8daafc-9c52-4e5e-b5cd-54e33c486d63</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
